netty:
  tcp-port: 8099
  boss-count: 1
  worker-count: 10
  keep-alive: true
  backlog: 100
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: ss123456
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
#business Thread pool
thread:
  pool:
    core-size: 1
    max-size: 10
    alive-time: 5
    queue-capacity: 60
